export const API_ROUTES = {
  AUTH: {
    USER: {
      LOGIN: '/user/login',
      SIGNUP: '/user/verify-otp',
      LOGOUT: '/user/logout',
      SESSION: '/user/session',
      RESEND_OTP: '/user/resend-otp',
      FORGOT_PASSWORD: '/user/forgot-password',
      VERIFY_FORGOT_PASSWORD_OTP: '/user/verify-forgot-password-otp',
      RESET_PASSWORD: '/user/reset-password',
    },
    TRAINER: {
      LOGIN: '/trainer/login',
      LOGOUT: '/trainer/logout',
      SESSION: '/trainer/session',
      REQUEST_OTP: '/trainer/request-otp',
      VERIFY_OTP: '/trainer/verify-otp',
      RESEND_OTP: '/trainer/resend-otp',
      FORGOT_PASSWORD: '/trainer/forgot-password',
      FORGOT_PASSWORD_RESEND_OTP: '/trainer/forgot-password-resend-otp',
      RESET_PASSWORD: '/trainer/reset-password',
      APPLY: '/trainer/apply',
    },
    GYM: {
      LOGIN: '/gym/login',
      LOGOUT: '/gym/logout',
      SESSION: '/gym/session',
      REQUEST_OTP: '/gym/auth/request-otp',
      VERIFY_OTP: '/gym/auth/verify-otp',
      REGISTER: '/gym/register',
      REAPPLY: '/gym/reapply',
      FORGOT_PASSWORD: '/gym/forgot-password',
      RESET_PASSWORD: '/gym/reset-password',
    },
    ADMIN: {
      LOGIN: '/admin/login',
      LOGOUT: '/admin/logout',
      SESSION: '/admin/session',
    },
  },
  USER: {
    PROFILE: '/user/profile',
    UPDATE_PROFILE: '/user/profile',
    MECH_CHECK: '/user/membership-check',
    ACTIVE_PLAN: '/user/active-plan',
  },
  TRAINER: {
    DETAILS: (id: string) => `/trainer/details/${id}`,
    CLIENTS: '/trainer/get-clients',
    CLIENT_DETAILS: (id: string) => `/trainer/client/${id}`,
    DASHBOARD_STATS: '/trainer/dashboard-stats',
    AVAILABILITY: '/trainer/availability',
    SLOTS: '/trainer/slots',
    SESSION_REQUESTS: '/trainer/session-requests',
    CHATS: '/trainer/chats',
    MESSAGES: (clientId: string) => `/trainer/chat/messages/${clientId}`,
  },
  GYM: {
    LIST: '/gyms',
    DETAILS: (id: string) => `/gyms/${id}`,
    EQUIPMENT: '/gym/equipment',
    SUBSCRIPTION_PLANS: '/gym/subscription-plans',
  },
  PAYMENT: {
    TRAINER_CHECKOUT: '/payment/create-checkout-session',
    GYM_CHECKOUT: '/payment/create-gym-checkout-session',
    TRANSACTIONS: '/payment/transactions',
  },
  WORKOUT: {
    LOG: '/workout/log',
    HISTORY: '/workout/history',
  },
  DIET: {
    LOG: '/diet/log',
    HISTORY: '/diet/history',
  },
  NOTIFICATION: {
    GET_ALL: '/notification',
    MARK_READ: (id: string) => `/notification/${id}/read`,
    MARK_ALL_READ: '/notification/read-all',
  },
  TEMPLATE: {
    WORKOUT: '/template/workout',
    DIET: '/template/diet',
  },
};
