export const API_ROUTES = {
  AUTH: {
    USER: {
      LOGIN: '/user/login',
      SIGNUP: '/user/verify-otp',
      LOGOUT: '/user/logout',
      SESSION: '/user/session',
      RESEND_OTP: '/user/resend-otp',
      FORGOT_PASSWORD: '/user/forgot-password',
      VERIFY_FORGOT_PASSWORD_OTP: '/user/verify-forgot-password-otp',
      RESET_PASSWORD: '/user/reset-password',
      REFRESH: '/user/refresh-token',
    },
    TRAINER: {
      LOGIN: '/trainer/login',
      LOGOUT: '/trainer/logout',
      SESSION: '/trainer/session',
      REQUEST_OTP: '/trainer/request-otp',
      VERIFY_OTP: '/trainer/verify-otp',
      RESEND_OTP: '/trainer/resend-otp',
      FORGOT_PASSWORD: '/trainer/forgot-password',
      FORGOT_PASSWORD_RESEND_OTP: '/trainer/forgot-password-resend-otp',
      RESET_PASSWORD: '/trainer/reset-password',
      APPLY: '/trainer/apply',
      REFRESH: '/trainer/refresh-token',
      REAPPLY: '/trainer/reapply',
    },
    GYM: {
      LOGIN: '/gym/login',
      LOGOUT: '/gym/logout',
      SESSION: '/gym/session',
      REQUEST_OTP: '/gym/auth/request-otp',
      VERIFY_OTP: '/gym/auth/verify-otp',
      REGISTER: '/gym/register',
      REAPPLY: '/gym/reapply',
      FORGOT_PASSWORD: '/gym/forgot-password',
      RESET_PASSWORD: '/gym/reset-password',
      REFRESH: '/gym/refresh-token',
    },
    ADMIN: {
      LOGIN: '/admin/login',
      LOGOUT: '/admin/logout',
      SESSION: '/admin/session',
      REFRESH: '/admin/refresh-token',
    },
  },
  USER: {
    PROFILE: '/user/get-profile',
    PROFILE_PAGE: '/user/profile-page',
    UPDATE_PROFILE: '/user/update-profile',
    MEMBERSHIP_CHECK: '/user/membership-check',
    ACTIVE_PLAN: '/user/active-plan',
    MY_GYM: '/user/my-gym',
    MY_TRAINER: '/user/my-trainer',
    CANCEL_MEMBERSHIP: '/user/gyms/cancel-membership',
    GYM_ANNOUNCEMENTS: '/user/gym-announcements',
    GYM_EQUIPMENT: '/user/gym-equipment',
    GYM_PRODUCTS: '/user/gym-products',
    GYM_WORKOUT_TEMPLATES: '/user/gym-workout-templates',
    GYMS: {
        LIST: '/user/gyms',
        DETAIL: (id: string) => `/user/gyms/${id}`,
        PLANS: (id: string) => `/user/gyms/${id}/subscription-plans`,
    },
    TRAINERS: {
        LIST: '/user/trainers',
        DETAIL: (id: string) => `/user/trainers/${id}`,
        RATINGS: (id: string) => `/user/trainer/ratings/${id}`,
        ADD_RATING: (id: string) => `/user/trainer/rating/${id}`,
    },
    GYM_RATINGS: (id: string) => `/user/gym/ratings/${id}`,
    ADD_GYM_RATING: (id: string) => `/user/gym/rating/${id}`,
    REVIEW: (id: string) => `/user/review/${id}`,
    MARK_ATTENDANCE: '/user/gym/mark-attendance',
    ATTENDANCE_HISTORY: (gymId: string) => `/user/gym/attendance-history/${gymId}`,
    WEIGHT: '/user/weight',
    ACTIVITY_DATA: '/user/activity-data',
    CHATS: '/user/chats',
    MESSAGES: (id: string) => `/user/chat/messages/${id}`,
    NOTIFICATIONS: '/user/notifications',
    PROGRESS: {
        BASE: '/user/progress',
        COMPARE: '/user/progress/compare',
    },
    WORKOUT_TEMPLATE_TOGGLE: '/user/workout-template/toggle',
  },
  USER_GYM_PRODUCT: {
    LIST: '/user/gym-products',
    WISH_LIST: '/user/gym-products/wishlist',
    ADD_TO_WISH_LIST: (id: string) => `/user/gym-products/wishlist/${id}`,
  },
  TRAINER: {
    GET_DETAILS: '/trainer/get-details',
    DASHBOARD_STATS: '/trainer/dashboard-stats',
    AVAILABILITY: '/trainer/availability',
    SLOTS: {
        BASE: '/trainer/slots',
        DETAIL: (id: string) => `/trainer/slots/${id}`,
    },
    SESSION_REQUESTS: {
        BASE: '/trainer/session-requests',
        DETAIL: (id: string) => `/trainer/session-requests/${id}`,
    },
    CLIENTS: {
        LIST: '/trainer/get-clients',
        DETAIL: (id: string) => `/trainer/user/${id}`,
    },
    WORKOUT: {
        ASSIGN: '/trainer/assign-workout',
        ADD_SESSION: (userId: string) => `/trainer/workout/add-session/${userId}`,
    },
    DIET: {
        ASSIGN: '/trainer/assign-diet',
    },
    CHATS: '/trainer/chats',
    MESSAGES: (clientId: string) => `/trainer/chat/messages/${clientId}`,
    PROFILE: '/trainer/profile',
    UPDATE_PROFILE: '/trainer/update-profile',
    TRANSACTIONS: '/trainer/transactions',
    SCHEDULE: '/trainer/weekly-schedule',
    CHANGE_PASSWORD: '/trainer/change-password',
  },
  GYM: {
    GET_DETAILS: '/gym/get-details',
    UPDATE_PROFILE: '/gym/update-profile',
    MEMBERS: '/gym/members',
    ATTENDANCE: '/gym/attendance',
    DASHBOARD_STATS: '/gym/dashboard-stats',
    PRODUCTS: {
        MANAGE: '/gym/products/manage',
        DETAIL: (id: string) => `/gym/products/manage/${id}`,
    },
    JOBS: {
        BASE: '/gym/jobs',
        DETAIL: (id: string) => `/gym/jobs/${id}`,
    },
    WORKOUT_TEMPLATES: {
        BASE: '/gym/workout-templates',
        DETAIL: (id: string) => `/gym/workout-templates/${id}`,
    },
    ANNOUNCEMENTS: {
        BASE: '/gym/announcements',
        DETAIL: (id: string) => `/gym/announcements/${id}`,
    },
    SUBSCRIPTION_PLAN: {
        BASE: '/gym/subscription-plan',
        LIST: '/gym/subscription-plans',
        DETAIL: (id: string) => `/gym/subscription-plan/${id}`,
    },
    EQUIPMENT: {
        BASE: '/gym/equipment',
        DETAIL: (id: string) => `/gym/equipment/${id}`,
        TOGGLE: (id: string) => `/gym/equipment/${id}/toggle`,
        AVAILABILITY: (id: string) => `/gym/equipment/${id}/availability`,
        CATEGORIES: '/gym/equipment-categories',
        CATEGORY_DETAIL: (id: string) => `/gym/equipment-categories/${id}`,
    }
  },
  ADMIN: {
    TRAINERS: {
        LIST: '/admin/trainers',
        DETAIL: (id: string) => `/admin/trainers/${id}`,
        STATUS: (id: string) => `/admin/trainers/${id}/status`,
        APPLICATION: (id: string) => `/admin/trainers/${id}/application`,
        REVIEWS: (id: string) => `/admin/trainers/${id}/reviews`,
    },
    GYMS: {
        LIST: '/admin/gyms',
        DETAIL: (id: string) => `/admin/gyms/${id}`,
        APPLICATION: (id: string) => `/admin/gyms/${id}/application`,
    },
    USERS: {
        LIST: '/admin/users',
        DETAIL: (id: string) => `/admin/users/${id}`,
    },
    TEMPLATES: {
        WORKOUT: '/admin/templates/workout',
        DIET: '/admin/templates/diet',
        DETAIL: (id: string) => `/admin/templates/${id}`,
    },
    TRANSACTIONS: {
        LIST: '/admin/transactions',
        EXPORT: '/admin/transactions/export',
    },
    DASHBOARD_STATS: '/admin/dashboard-stats',
    DASHBOARD_GRAPH: '/admin/dashboard-graph',
    RATINGS: '/admin/ratings',
    SESSION: '/admin/session',
  },
  PAYMENT: {
    TRAINER_CHECKOUT: '/payment/create-checkout-session',
    GYM_CHECKOUT: '/payment/create-gym-checkout-session',
    TRANSACTIONS: '/payment/transactions',
  },
  WORKOUT: {
    BASE: '/user/workouts',
    LOG: '/workout/log',
    HISTORY: '/workout/history',
    DAYS: '/workout/days',
    ADMIN_TEMPLATES: '/workout/admin/workout-templates',
    GET_SESSIONS: '/workout/get-sessions',
    SESSIONS: {
        BASE: '/workout/sessions',
        DETAIL: (id: string) => `/workout/sessions/${id}`,
    },
    DETAILS: (id: string) => `/workout/${id}`,
    DELETE: (id: string) => `/workout/${id}`,
  },
  DIET: {
    BASE: '/diet',
    MEALS: (date: string) => `/diet/${date}/meals`,
    MEAL_ACTION: (date: string, mealId: string) => `/diet/${date}/meals/${mealId}`,
    PLAN: '/diet/plan',
    ADD: '/diet/add',
  },
  NOTIFICATION: {
    GET_ALL: '/notification',
    MARK_READ: (id: string) => `/notification/${id}/read`,
    MARK_ALL_READ: '/notification/read-all',
  },
  TEMPLATE: {
    WORKOUT: {
        BASE: '/template/workout',
        DETAIL: (id: string) => `/template/workout/${id}`,
        START: '/template/workout/start',
        STOP: '/template/workout/stop',
    },
    DIET: {
        BASE: '/template/diet',
        DETAIL: (id: string) => `/template/diet/${id}`,
        START: '/template/diet/start',
        STOP: '/template/diet/stop',
    },
    DETAILS: (id: string) => `/template/details/${id}`,
  },
};
