export const ROUTES = {
  //User Routes
  CHOOSE_LOGIN: "/login",
  USER_LOGIN: "/user/login",
  USER_FORGOT_PASSWORD: "/forgot-password",
  USER_NEW_PASSWORD: "/new-password",
  USER_SIGNUP: "/signup",
  USER_HOME: "/",
  USER_HOME_ALT: "/home",
  USER_PROFILE: "/profile",
  USER_EDIT_PROFILE: "/edit-profile",
  USER_TRANSACTIONS:'/transactions',
  USER_DASHBOARD:'/dashboard',
  USER_VERIFY_OTP: "/verify-otp",
  USER_TRAINER_PAGE:'/trainers',
  USER_INDIVIDUAL_TRAINER:'/trainers/:id',
  MY_TRAINER_PROFILE:'/my-trainer/profile',
  USER_WORKOUTS_PAGE:'/workouts',
  USER_ADMIN_WORKOUT_TEMPLATES:'/workouts/browse',
  USER_ADD_WORKOUT:'/workouts/add',
  USER_ADD_WORKOUT_SESSION:'/workouts/add-session',
  USER_EDIT_WORKOUT_SESSION:'/workouts/:id',
  USER_START_WORKOUT:'/workouts/:id/start',
  USER_WORKOUT_SUCCESS:'/workouts/:id/success',

  USER_DIET:'/diets',
  USER_ADD_DIET:'/diets/add',


  CALLBACK:"/callback",
  USER_NOT_FOUND:"*",

  // Trainer Routes
  TRAINER_LOGIN: "/trainer/login",
  TRAINER_FORGOT_PASSWORD: "/trainer/forgot-password",
  TRAINER_FORGOT_PASSWORD_VERIFY_OTP: "/trainer/forgot-password/verify",
  TRAINER_RESET_PASSWORD: "/trainer/reset-password",
  TRAINER_APPLY: "/trainer/apply",
  TRAINER_VERIFY_OTP: "/trainer/verify-otp",
  TRAINER_WAITLIST: "/trainer/waitlist",
  TRAINER_REJECTED: "/trainer/rejected",
  TRAINER_DASHBOARD: "/trainer/dashboard",
  TRAINER_INDIVIDUAL_CLIENT: "/trainer/user/:id",
  TRAINER_CLIENT_WORKOUT: "/trainer/workout/:clientId",
  TRAINER_CLIENT_SESSION: "/trainer/workout/add-session/:clientId",

  TRAINER_CLIENT_DIET: "/trainer/diet/:clientId",

  // Gym Routes
  GYM_LOGIN: "/gym/login",
  GYM_APPLY: "/gym/apply",
  GYM_VERIFY_OTP: "/gym/verify-otp",
  GYM_WAITLIST: "/gym/waitlist",
  GYM_DASHBOARD: "/gym/dashboard",

  // Admin Routes
  ADMIN_LOGIN: "/admin/login",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_TRAINERS: "/admin/trainers",
  ADMIN_TRAINER_DETAILS: "/admin/trainers/:trainerId",
  ADMIN_TRAINER_APPLICATION: "/admin/trainers/:trainerId/application",
  ADMIN_USERS: "/admin/users",
  ADMIN_USER_DETAILS: "/admin/users/:userId",
  ADMIN_GYMS: "/admin/gyms",
  ADMIN_GYM_APPLICATION: "/admin/gyms/:id/application",
  ADMIN_TEMPLATE_MANAGEMENT: "/admin/templates",
  ADMIN_ADD_WORKOUT_TEMPLATE: "/admin/templates/new/workout",
  ADMIN_ADD_DIET_TEMPLATE: "/admin/templates/new/diet",
  ADMIN_EDIT_TEMPLATE: "/admin/templates/:id/:template/edit",
};