export const ROUTES = {
  //User Routes
  CHOOSE_LOGIN: "/",
  GLOBAL_LOGIN: "/login",
  USER_LOGIN: "/user/login",
  USER_FORGOT_PASSWORD: "/forgot-password",
  USER_NEW_PASSWORD: "/new-password",
  USER_SIGNUP: "/signup",
  USER_HOME_ALT: "/home",
  USER_NOTIFICATIONS: "/notifications",
  USER_PROFILE: "/profile",
  USER_EDIT_PROFILE: "/edit-profile",
  USER_TRANSACTIONS: '/transactions',
  USER_DASHBOARD: '/dashboard',
  USER_VERIFY_OTP: "/verify-otp",
  USER_TRAINER_PAGE: '/trainers',
  USER_INDIVIDUAL_TRAINER: '/trainers/:id',
  MY_TRAINER_PROFILE: '/my-trainer/profile',
  MY_TRAINER_SESSIONS: '/my-trainer/sessions',
  MY_TRAINER_CHAT: '/my-trainer/chat/:id',
  MY_TRAINER_AVAILABILITY: '/my-trainer/availability',
  VIDEO_CALL: '/video-call/:roomId',


  USER_GYMS: '/gyms',
  USER_INDIVIDUAL_GYM: '/gyms/:id',
  USER_MY_GYM: '/gyms/my-gym',
  USER_GYM_DASHBOARD: '/gyms/dashboard',
  USER_GYM_ANNOUNCEMENTS: '/gyms/announcements',

  USER_WORKOUTS_PAGE: '/workouts',
  USER_ADMIN_WORKOUT_TEMPLATES: '/workouts/browse',
  USER_ADD_WORKOUT: '/workouts/add',
  USER_ADD_WORKOUT_SESSION: '/workouts/add-session',
  USER_EDIT_WORKOUT_SESSION: '/workouts/:id',
  USER_START_WORKOUT: '/workouts/:id/start',
  USER_WORKOUT_SUCCESS: '/workouts/:id/success',

  USER_DIET: '/diets',
  USER_ADD_DIET: '/diets/add',

  CALLBACK: "/callback",
  USER_NOT_FOUND: "*",

  // Trainer Routes
  TRAINER_LOGIN: "/trainer/login",
  TRAINER_FORGOT_PASSWORD: "/trainer/forgot-password",
  TRAINER_FORGOT_PASSWORD_VERIFY_OTP: "/trainer/forgot-password/verify",
  TRAINER_RESET_PASSWORD: "/trainer/reset-password",
  TRAINER_APPLY: "/trainer/apply",
  TRAINER_VERIFY_OTP: "/trainer/verify-otp",
  TRAINER_WAITLIST: "/trainer/waitlist",
  TRAINER_REJECTED: "/trainer/rejected",
  TRAINER_DASHBOARD: "/trainer/dashboard",
  TRAINER_NOTIFICATIONS: "/trainer/notifications",
  TRAINER_CLIENTS: "/trainer/clients",
  TRAINER_TRANSACTIONS: "/trainer/transactions",
  TRAINER_PROFILE: "/trainer/profile",
  TRAINER_SLOTS: "/trainer/slots",
  TRAINER_WEEKLY_SCHEDULE: "/trainer/weekly-schedule",
  TRAINER_INDIVIDUAL_CLIENT: "/trainer/user/:id",
  TRAINER_CLIENT_CHAT: "/trainer/chat/:clientId",
  TRAINER_CLIENT_VIDEO_CALL: "/trainer/video-call/:roomId",
  TRAINER_SESSION_REQUESTS: "/trainer/session-requests",
  TRAINER_CLIENT_WORKOUT: "/trainer/workout/:clientId",
  TRAINER_CLIENT_SESSION: "/trainer/workout/add-session/:clientId",
  TRAINER_CLIENT_DIET: "/trainer/diet/:clientId",

  // Gym Routes
  GYM_LOGIN: "/gym/login",
  GYM_APPLY: "/gym/apply",
  GYM_VERIFY_OTP: "/gym/verify-otp",
  GYM_WAITLIST: "/gym/waitlist",
  GYM_DASHBOARD: "/gym/dashboard",
  GYM_REAPPLY: "/gym/reapply",
  GYM_SUBSCRIPTIONS: "/gym/subscriptions",
  GYM_SUBSCRIPTIONS_NEW: "/gym/subscriptions/new",
  GYM_SUBSCRIPTIONS_EDIT: "/gym/subscriptions/edit/:id",
  GYM_ANNOUNCEMENTS: "/gym/announcements",
  GYM_ANNOUNCEMENTS_NEW: "/gym/announcements/new",
  GYM_ANNOUNCEMENTS_EDIT: "/gym/announcements/edit/:id",
  GYM_ATTENDANCE: "/gym/attendance",

  // Admin Routes
  ADMIN_LOGIN: "/admin/login",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_TRAINERS: "/admin/trainers",
  ADMIN_TRAINER_DETAILS: "/admin/trainers/:trainerId",
  ADMIN_TRAINER_APPLICATION: "/admin/trainers/:trainerId/application",
  ADMIN_USERS: "/admin/users",
  ADMIN_USER_DETAILS: "/admin/users/:userId",
  ADMIN_GYMS: "/admin/gyms",
  ADMIN_GYM_APPLICATION: "/admin/gyms/:id/application",
  ADMIN_TEMPLATE_MANAGEMENT: "/admin/templates",
  ADMIN_ADD_WORKOUT_TEMPLATE: "/admin/templates/new/workout",
  ADMIN_ADD_DIET_TEMPLATE: "/admin/templates/new/diet",
  ADMIN_EDIT_TEMPLATE: "/admin/templates/:id/:template/edit",
};